os:
- linux
- osx
- windows
language:       ruby
rvm:
- 2.6.3
- 2.4.6
- 2.5.5
- 2.3.8
- 2.2.10
- 2.1.10
- 2.0.0-p648
- 1.9.3-p551
- 1.8.7-p374
- 1.6.7
env:
  global:
    secure:     VchDDae2eYvQnsDXVDYb0V//LTxigkFsiLEGSw7meyfqS14T12k4q0b9rtCRaldjsUHs9L/vfv2qdu+ysafe3XvfL76ny7aYuupR4isFxHGADVvfaiiZCPUbaUsMQ92UzuopD5mpB5irnOWiNkq2xoyvG4wp27VKDKt1rbg2KjYz6OYG0/muk/VbJnxIW0IpMwaOJ63JlNGzuvf7rpkEmDlHHty1tnS4b5XCYQ2TjMBVQ3mdJiGdOC1mjTfRtVG/a478bTpHehpav4bqvviQKeyFbuAgqa9zqmG7LLZB7+Ep4Agfrk7tENhPc/AiYrTpFxulc8uLPER5Ol0gsj25dlJOhhQZUaD/XK37ZbgEQ2drxk7Y5FCNH5qD5Oy6ar3kyt+2K5pBw8+cukaABdYi/Ii5rdjGhUaQvJ7K5DV1C5CEwBn5YPhg2wt1RtIWsBj8dIuDjXEv+D+Nup6L//+8XowauKhdobel3zVvpfKB93H/aM2c/1xhmcn5F8F/l3XHwzFBGprqmTLvz1ca8DUCogdzYfqTfRXM41zmmvGh/EuvQZ+R9J/hR+SevK9asNMr0ZmSBkkyJh7iz2gyUrPHJQ4oXZZWE5hpxk5qonS/tNM+YKj3BPcVSLUF/oWabmpvZe/1m6nMLbDgvaG7I/E5tHqJh3JZ8n7cPssaLcXgPd0=
before_install:
- export SC_CLIENT_ID=$SOUNDCLOUD_CLIENT_ID soundcloud9000
install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install portaudio; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mpg123; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then gem install soundcloud9000; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then gem uninstall audite; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then gem install --user audite -- --with-ldflags="-lmpg123"; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt-get install portaudio19-dev libmpg123-dev libncurses-dev ruby1.9.1-dev; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gem install soundcloud9000; fi
script:
- soundcloud9000
