language: ruby
rvm:
  # - ruby-2.7.1
  # - ruby-2.6.6
  # - ruby-2.5.8
  - ruby-2.5.1
  # - ruby-2.4.10
  # - ruby-2.3.8
  # - ruby-2.2.10
  # - ruby-2.1.10
  # - ruby-1.9.3-p551
  # - ruby-1.9.2
  # - ruby-2.0.0-p648
  # - jruby-head
jobs:
  include:
    - os: osx
    - os: linux
      dist: bionic
    # - os: linux
    #   dist: xenial
    # ruby-dev on xenial and trusty is 2.3
    # - os: linux
    #   dist: trusty
    # ruby-dev on trusty is 1.9.1 and curses requires ruby >= 2.1.0
    # - os: linux
    #   dist: precise
    # sudo gem does not work on precise
env:
  global:
    secure: H+9rrcXIzXWGKq9UXHaIkNN4mn3tev9jI4ihKdLRvr0Bs/NzfF6ae18yxYxf7hyiDZFtflEpPP3KhAqecrSyzYXKUVNpuHUUQChOOSFuKSFjryHVR3rtwXnzfXO5K/XkREfgMkBab8rpctPrP62KL+CqNQPxZdbOYBN5fndqdjiWHk5Gfdqsl5beQVo16GQ3iRaQBaXJasTOfLf0Pr1DDVVTuTSz1vn8IjbXaRnoWZ6QEdYvqWGpIDEMIOdWvUfLgoeaHq+HWjsfILJDxyk6RuYRtnEEHvi0vB8KazSO29dCHKRghJB00mBUtU/z9hVScE2J/8MPbi0HjH3Yvq9PZbQIQBCsQr+zOVF/R/EEk7NfAS8PU061fQBwOZ9zKkDLFARzrNpQXjUBucm1+HJiitjYOT+uQ+7nY1YUjqj4ez/ppmgPdziqbSAP98IED/Swb+35D4F1WQan0xQt+GfK5u0Hf0GIKymBjBUUYy2rSY0EKaT3iFXxC5qIH7aiavTqq6JnFzQttuW5CfS9GMDPn9+X2nqj/npSwjWSOKuzWbs12+Z6hMOrXcUhV6vme9ul/PiWsfhb97x8LTpsdnPh1ElLrl7gYHF56cIISknEGMDiYzLhA1frWavajIKMvgeOSksp+LBR59n5WkoBAUcL0aNr1yaERxMBfFFi3KqWACQ=
install:
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install portaudio; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mpg123; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then gem install soundcloud9000; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yes y | gem uninstall audite --force; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then gem install --user audite -- --with-ldflags="-lmpg123"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rvm get head; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install portaudio19-dev libmpg123-dev libncurses-dev ruby-dev; fi
  - gem install bundler:1.17.1
script:
  - gem build soundcloud9000.gemspec
  - sudo gem install soundcloud9000-0.1.3.gem
  - sudo gem uninstall soundcloud9000-0.1.3.gem
  - bundle _1.17.1_ install --path vendor/bundle
  - bundle _1.17.1_ exec rake install:local
