name: soundcloud9000
base: core18
version: '0.1.3+git'
summary: The next generation SoundCloud client
description: |
  A SoundCloud terminal client, without all the stupid CSS files.

grade: stable
confinement: strict

parts:
  soundcloud9000:
    source: .
    plugin: ruby
    # ruby-version: '2.6.6'
    build-packages:
      - git
apps:
  soundcloud9000:
    command: ../project/bin/soundcloud9000
